eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
logging:
    level:
        com:
            netflix:
                discovery: DEBUG
                eureka: DEBUG
        io:
            micrometer:
                tracing: TRACE
            zipkin:
                reporter: DEBUG
        org:
            springframework:
                cloud:
                    gateway: DEBUG
                    netflix:
                        eureka: DEBUG
management:
    endpoint:
        prometheus:
            enabled: true
    endpoints:
        web:
            exposure:
                include: health,info,prometheus
    metrics:
        export:
            enabled: true

    tracing:
        enabled: true
        sampling:
            probability: 1.0
    zipkin:
        endpoint: http://localhost:9411/api/v2/spans
spring:
    cloud:
        gateway:
            routes:
            -   id: inventory-service
                predicates:
                - Path=/inventory/**
                uri: lb://InverntoryService
            -   id: product-service
                predicates:
                - Path=/product/**
                uri: lb://PRODUCTSERVICE
            -   id: order-serivice
                predicates:
                - Path=/order/**
                uri: lb://OrderService
